logging:
  config: classpath:logback-spring-dev.xml

server:
  port: 9101
  servlet:
    context-path: /openai/wxkf

spring:
  redis:
    database: 0
    username:
    password:
    host:
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-wait: -1
        max-idle: 10
        min-idle: 0
        max-active: 50

# 微信客服配置
wx:
  kf:
    token:
    encodingAesKey:
    # 企业id
    sCorpId:
    # 获取token
    getAccessTokenUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=&corpsecret=
    # 同步消息
    syncMsgUrl: https://qyapi.weixin.qq.com/cgi-bin/kf/sync_msg?access_token=%s
    # 发送消息
    sendMsgUrl: https://qyapi.weixin.qq.com/cgi-bin/kf/send_msg?access_token=%s

# chat openai api
openai:
  url: https://api.openai.com/v1/completions
  key: